{
 "title": "XiaomiMiBand5",
 "time": { "from": "2021-03-21T10:02:50.965Z", "to": "2021-04-14T20:05:17.099Z" },
 "panels": [
  {
   "title": "HeartRate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(heartRate) FROM \"XiaomiMiBand5\".\"autogen\".\"Activity\" GROUP BY time(5m)\n\n\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hours of Sleep per day",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"rawKind\")/60 AS Sleep FROM \"Activity\" WHERE $timeFilter AND rawKind>=100  GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Steps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" }
     ],
     "measurement": "Activity",
     "select": [
      [
       { "params": [ "steps" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "steps" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sleep",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"rawKind\")/60 AS deepSleep FROM \"Activity\" WHERE $timeFilter AND rawKind>=100 AND rawKind <= 125 GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"rawKind\")/60 AS lightSleep FROM \"Activity\" WHERE $timeFilter AND (rawKind>=220) GROUP BY time(24h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "rawIntensity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "Activity",
     "select": [
      [
       { "params": [ "rawIntensity" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "rawKind",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "Activity",
     "select": [
      [
       { "params": [ "rawKind" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}